[project]

# Information
site_name = "XGMML Reader and Writer"
site_description = "XGMML 读写器 | XGMML Reader and Writer"
site_author = "范叶亮 | Leo Van"
site_url = "https://xgmml.leovan.tech"
copyright = """
版权所有 &copy; 2025-2026，<a href="https://leovan.me" target="_blank">范叶亮 | Leo Van</a>
"""

# Repository
repo_name = "leovan/xgmml"
repo_url = "https://github.com/leovan/xgmml"

# Javascript
extra_javascript = [
  "javascripts/mathjax.js",
  "https://cdn.jsdmirror.com/npm/mathjax@4/tex-chtml.js",
  "https://cdn.jsdmirror.com/npm/tablesort@5.7.0/dist/tablesort.min.js",
  "javascripts/tablesort.js",
]

# Style
extra_css = [
  "stylesheets/extra.css",
]

# Navigation
nav = [
  "index.md",
  { "English" = [
    "en/index.md",
    "en/api.md",
    "en/parameters.md",
    "en/style.md",
    "en/custom.md",
    "en/examples.md",
  ] },
  { "中文" = [
    "zh/index.md",
    "zh/api.md",
    "zh/parameters.md",
    "zh/style.md",
    "zh/custom.md",
    "zh/examples.md",
  ] },
]

# Theme
[project.theme]

favicon = "images/logo.png"
logo = "images/logo.png"

language = "zh"

features = [
  "announce.dismiss",
  "content.code.annotate",
  "content.code.copy",
  "content.code.select",
  "content.footnote.tooltips",
  "content.tabs.link",
  "content.tooltips",
  "navigation.footer",
  "navigation.indexes",
  "navigation.instant",
  "navigation.instant.prefetch",
  "navigation.path",
  "navigation.sections",
  # "navigation.tabs",
  "navigation.top",
  "navigation.tracking",
  "search.highlight",
]

[[project.theme.palette]]
scheme = "default"
primary = "amber"
accent = "amber"
toggle.icon = "lucide/sun"
toggle.name = "切换至暗黑模式"

[[project.theme.palette]]
scheme = "slate"
primary = "amber"
accent = "amber"
toggle.icon = "lucide/moon"
toggle.name = "切换至亮色模式"

[project.theme.icon]
repo = "fontawesome/brands/git-alt"

# Extra
[project.extra]
alternate = [
  { name = "English", link = "/en/", lang = "en" },
  { name = "简体中文", link = "/zh/", lang = "zh" }
]

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/leovan"

[[project.extra.social]]
icon = "fontawesome/solid/house"
link = "https://leovan.me"

[project.extra.analytics]
provider = "google"
property = "G-GZ809KZHVG"

# Extensions
[project.markdown_extensions.abbr]
[project.markdown_extensions.admonition]
[project.markdown_extensions.attr_list]
[project.markdown_extensions.def_list]
[project.markdown_extensions.footnotes]
[project.markdown_extensions.md_in_html]
[project.markdown_extensions.tables]

[project.markdown_extensions.toc]
permalink =  true
toc_depth = 3

[project.markdown_extensions.toc.slugify]
object = "pymdownx.slugs.slugify"
kwds = { case = "lower" }

[project.markdown_extensions.pymdownx.arithmatex]
generic = true

[project.markdown_extensions.pymdownx.blocks.caption]
[project.markdown_extensions.pymdownx.caret]
[project.markdown_extensions.pymdownx.details]

[project.markdown_extensions.pymdownx.emoji]
emoji_index = "zensical.extensions.emoji.twemoji" 
emoji_generator = "zensical.extensions.emoji.to_svg"

[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
line_spans = "__span"
pygments_lang_class = true

[project.markdown_extensions.pymdownx.inlinehilite]
[project.markdown_extensions.pymdownx.keys]
[project.markdown_extensions.pymdownx.mark]
[project.markdown_extensions.pymdownx.progressbar]
[project.markdown_extensions.pymdownx.snippets]

[project.markdown_extensions.pymdownx.superfences]
custom_fences = [
  { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" }
]

[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true
combine_header_slug = true

[project.markdown_extensions.pymdownx.tabbed.slugify]
object = "pymdownx.slugs.slugify"
kwds = { case = "lower" }

[project.markdown_extensions.pymdownx.tasklist]
custom_checkbox = true

[project.markdown_extensions.pymdownx.tilde]
